import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Define Eurostile fonts
const eurostileBold = localFont({
  src: "./fonts/EurostileBold.ttf",
  variable: "--font-eurostile-bold",
  weight: "700",
});

const eurostileCondensedBold = localFont({
  src: "./fonts/EurostileCnd-Bold Regular.ttf",
  variable: "--font-eurostile-condensed-bold",
  weight: "700",
});

const eurostileExtendedBold = localFont({
  src: "./fonts/EurostileExt-Bold Regular.ttf",
  variable: "--font-eurostile-extended-bold",
  weight: "700",
});

const eurostileExtendedNormal = localFont({
  src: "./fonts/EurostileExt-Normal Regular.ttf",
  variable: "--font-eurostile-extended-normal",
  weight: "400",
});

const eurostileOblique = localFont({
  src: "./fonts/EurostileOblique.ttf",
  variable: "--font-eurostile-oblique",
  style: "italic",
  weight: "400",
});

// Define Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root Layout Component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${eurostileBold.variable} ${eurostileCondensedBold.variable} ${eurostileExtendedBold.variable} ${eurostileExtendedNormal.variable} ${eurostileOblique.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
